/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_agivision_concentrator_server_device_SerialPort */

#ifndef _Included_com_wenyuntech_serialporttest_device_SerialPort
#define _Included_com_wenyuntech_serialporttest_device_SerialPort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_agivision_concentrator_server_device_SerialPort
 * Method:    open
 * Signature: (Ljava/lang/String;I)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_com_com_wenyuntech_serialporttest_device_SerialPort_open
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     com_agivision_concentrator_server_device_SerialPort
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_com_wenyuntech_serialporttest_device_SerialPort_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
